version: '3.1'

services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: <endpoint_rds>
      WORDPRESS_DB_USER: <usuario>
      WORDPRESS_DB_PASSWORD: <senha>
      WORDPRESS_DB_NAME: <nome_do_banco>
    volumes:
      - /home/ec2-user/efs:/var/www/html