version: '3.1'
services:
  wordpress:
    image: wordpress:5.6.0-php7.4
    restart: always
    ports:
      - 80:80
    volumes:
      - /home/ec2-user/efs:/var/www/html
    env_file:
      - /home/ec2-user/efs/wp.env